server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: authService
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: adminService
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: streamService
          uri: lb://STREAM-SERVICE
          predicates:
            - Path=/stream/**
          filters:
            - StripPrefix=1
        - id: managerService
          uri: lb://MANAGER-SERVICE
          predicates:
            - Path=/manager/**
          filters:
            - StripPrefix=1
        - id: frontend
          uri: lb://STREAM-SERVICE
          predicates:
            - Path=/**

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true

